<link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Thang_Banner::css/jquery.bxslider.css') ?>"/>

<ul class="bxslider">
<?php
    $data = $this->getData('banners');
    $auto = $this->getData('auto') ? "true" : "false";
    $pager = $this->getData('pager') ? "true" : "false";
    $speed = intval($this->getData('speed'));

    foreach ($data as $d) {
        ?>
        <li>
            <a href="<?php echo $d['link'] ?>">
                <img src="<?php echo $this->getData('mediaURL') . $d['image']; ?>" title="<?php echo $d['content']; ?>"/>
            </a>
        </li>
        <?php
    }
?>
</ul>

<script>
    require(['jquery', 'bxslider'], function ($) {
        $(function () {
            $('.bxslider').bxSlider({
                auto: <?php echo $auto ?>,
                pager: <?php echo $pager ?>,
                speed: <?php echo $speed ?>,
                captions: true
            });
        });
    });
</script>
